
#server:
#  port: 9091
#
#spring:
#  datasource:
#    url: jdbc:mysql://localhost:3306/ziff?createDatabaseIfNotExist=true
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    username: root
#    password: !Sudi67!
#  jpa:
#    database: mysql
#    database-platform: org.hibernate.dialect.MySQLDialect
#    generate-ddl: true
#    show-sql: true
#    hibernate:
#      ddl-auto: update
#
#  mail:
#    host: smtp.gmail.com
#    port: 587
#    username: kekovasudi@gmail.com
#    password: jsftuwhuwgdgbntu
#
#    properties:
#      mail:
#        smtp:
#          auth: true
#          connectiontimeout: 20000
#          timeout: 20000
#          writetimeout: 20000
#
#          starttls:
#            enable: true
#
#    default-encoding: UTF-8
#    protocol: smtp
#
#springdoc:
#  swagger-ui:
#    path: /ziff-api
#    disable-swagger-default-url: true
#    try-it-out-enabled: true
#    operations-sorter: method
#    tags-sorter: alpha
#    filter: true
#  api-docs:
#    path: /ziff-api-doc
#  packages-to-scan: com.ziff.controller




